groups:
    - developer
recipes:
    mac_os_x:
        - osxdefaults::set_computer_name
attributes:
    osxdefaults:
        computername: shrike01
    homebrewalt:
        apps:
            - git-extras
        cask_apps:
            - sourcetree